services:
  web:
    build: ./front-end
    depends_on:
      - backend

  backend:
    build: ./back-end

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - web
      - backend